import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { CircuitBackground } from "@/components/circuit-background";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Codable Privacy Policy",
  description: "Privacy policy for Codable, Jeremy Collins' iOS Safari web developer tools app.",
  alternates: {
    canonical: "/codable-privacy-policy",
  },
  openGraph: {
    title: "Codable Privacy Policy",
    description: "Privacy policy for Codable, an iOS Safari web developer tools app.",
    url: "/codable-privacy-policy",
    type: "article",
  },
};

export default function CodablePrivacyPolicy() {
  return (
    <div className="relative min-h-screen">
      <CircuitBackground />
      <div className="relative z-10">
        <Header />
      <main className="pt-24 pb-16">
        <div className="max-w-4xl mx-auto px-6">
          {/* Page header */}
          <div className="mb-12">
            <span className="text-neon-cyan font-mono text-sm tracking-wider">
              {"// LEGAL"}
            </span>
            <h1 className="font-display text-3xl md:text-4xl font-bold mt-4 mb-2">
              <span className="text-foreground">Codable</span>{" "}
              <span className="text-neon-green">Privacy Policy</span>
            </h1>
            <p className="text-muted-foreground font-mono text-sm">
              Effective date: March 10, 2019
            </p>
          </div>

          {/* Content */}
          <article className="prose prose-invert max-w-none">
            <div className="space-y-8 text-muted-foreground">
              <p className="leading-relaxed">
                Codable (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates the Codable mobile
                application (hereinafter referred to as the &quot;Service&quot;).
              </p>

              <p className="leading-relaxed">
                This page informs you of our policies regarding the collection,
                use, and disclosure of personal data when you use our Service
                and the choices you have associated with that data.
              </p>

              <p className="leading-relaxed">
                We use your data to provide and improve the Service. By using
                the Service, you agree to the collection and use of information
                in accordance with this policy. Unless otherwise defined in this
                Privacy Policy, the terms used in this Privacy Policy have the
                same meanings as in our Terms and Conditions.
              </p>

              {/* Definitions */}
              <section className="border-l-2 border-neon-green pl-6">
                <h2 className="font-display text-xl text-foreground mb-4">
                  Definitions
                </h2>

                <div className="space-y-4">
                  <div>
                    <h3 className="font-mono text-neon-cyan text-sm mb-1">
                      Service
                    </h3>
                    <p className="text-sm leading-relaxed">
                      Service is the Codable mobile application operated by
                      Codable
                    </p>
                  </div>

                  <div>
                    <h3 className="font-mono text-neon-cyan text-sm mb-1">
                      Personal Data
                    </h3>
                    <p className="text-sm leading-relaxed">
                      Personal Data means data about a living individual who can
                      be identified from those data (or from those and other
                      information either in our possession or likely to come
                      into our possession).
                    </p>
                  </div>

                  <div>
                    <h3 className="font-mono text-neon-cyan text-sm mb-1">
                      Usage Data
                    </h3>
                    <p className="text-sm leading-relaxed">
                      Usage Data is data collected automatically either
                      generated by the use of the Service or from the Service
                      infrastructure itself (for example, the duration of a page
                      visit).
                    </p>
                  </div>
                </div>
              </section>

              {/* Information Collection */}
              <section className="border-l-2 border-neon-magenta pl-6">
                <h2 className="font-display text-xl text-foreground mb-4">
                  Information Collection and Use
                </h2>

                <div className="space-y-4 text-sm leading-relaxed">
                  <p>
                    The service collects no identifiable information beyond that
                    which is provided by the App Store Connect usage statistics.
                    No data is sent or stored in third-party locations, other
                    than App Store Connect.
                  </p>

                  <p>
                    When you access the Service through a mobile device, this
                    information may be collected automatically, which includes
                    the type of mobile device you use, your mobile operating
                    system, and whether a session was initiated.
                  </p>

                  <p>
                    The service is used to load user-requested URLs from the
                    internet, but this data transaction is entirely constrained
                    to within the client-side app service. User-entered data, or
                    any data gathered from loaded websites is not retained or
                    transmitted.
                  </p>
                </div>
              </section>

              {/* Changes */}
              <section className="border-l-2 border-neon-cyan pl-6">
                <h2 className="font-display text-xl text-foreground mb-4">
                  Changes to This Privacy Policy
                </h2>

                <p className="text-sm leading-relaxed">
                  The service may update its Privacy Policy from time to time.
                  You are advised to review this Privacy Policy page
                  periodically for any changes.
                </p>
              </section>

              {/* Contact */}
              <section className="border border-border bg-card/30 p-6 mt-8">
                <h2 className="font-display text-xl text-foreground mb-4">
                  Contact Us
                </h2>
                <p className="text-sm leading-relaxed">
                  If you have any questions about this Privacy Policy, please
                  contact{" "}
                  <a
                    href="mailto:jeremy@jeremycollins.net"
                    className="text-neon-green hover:underline"
                  >
                    jeremy@jeremycollins.net
                  </a>
                </p>
              </section>
            </div>
          </article>
        </div>
      </main>
      <Footer />
      </div>
    </div>
  );
}
